spring:
  application:
    name: AIService

  output:
    ansi:
      enabled: always

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-1.5-flash

server:
  port: 8082
  servlet:
    context-path: /api/v1

python:
  predict:
    url: http://localhost:8000/predict

#debug: true
